"""empty message

Revision ID: 09696e898d21
Revises: 2ab632775f1b
Create Date: 2021-04-22 15:09:24.975570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09696e898d21'
down_revision = '2ab632775f1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Request', sa.Column('approved_by_id', sa.Integer(), nullable=True))
    op.drop_constraint('Request_approved_by_fkey', 'Request', type_='foreignkey')
    op.create_foreign_key(None, 'Request', 'User', ['approved_by_id'], ['id'])
    op.drop_column('Request', 'approved_by')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Request', sa.Column('approved_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Request', type_='foreignkey')
    op.create_foreign_key('Request_approved_by_fkey', 'Request', 'User', ['approved_by'], ['id'])
    op.drop_column('Request', 'approved_by_id')
    # ### end Alembic commands ###
