"""empty message

Revision ID: abc9bb5b1944
Revises: bd4170383a1a
Create Date: 2021-05-03 23:02:22.059496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abc9bb5b1944'
down_revision = 'bd4170383a1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Request', sa.Column('denied_remarks', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Request', 'denied_remarks')
    # ### end Alembic commands ###
