"""empty message

Revision ID: ace64bf4644c
Revises: 09696e898d21
Create Date: 2021-04-28 21:02:01.556761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ace64bf4644c'
down_revision = '09696e898d21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('RequestLine', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('RequestLine', 'name')
    # ### end Alembic commands ###
