"""empty message

Revision ID: d201218ce644
Revises: 
Create Date: 2021-04-20 19:10:42.741538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd201218ce644'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Request', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('Request', sa.Column('updated_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Request', 'updated_on')
    op.drop_column('Request', 'created_on')
    # ### end Alembic commands ###
