"""empty message

Revision ID: d5fd35c64ccf
Revises: 64fec018b871
Create Date: 2021-05-04 16:33:34.167646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5fd35c64ccf'
down_revision = '64fec018b871'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'InventoryItem', 'Inventory', ['inventory_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'InventoryItem', type_='foreignkey')
    # ### end Alembic commands ###
